sudo: required
services:
 - docker

before_install:
 - docker build -t anttia/docker-react -f Dockerfile.dev .

script:
 - docker run anttia/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "SG-Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-943703639214"
  bucket_path: "SG-Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  